# Generated by Django 4.0.2 on 2022-03-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='body',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='heading',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
